version: '3.8'

services:
  db:
    image: mysql:8.0.30
    command: --default-authentication-plugin=mysql_native_password
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: servico_agenda
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"  
    networks:
      - agenda-network

  rabbitmq-server:
    container_name: rabbitmq-server
    image: rabbitmq:3.11-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - agenda-network

  servico-agenda:
    container_name: servico-agenda
    build: .
    image: felipe390/servico-agenda:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/servico_agenda?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
    depends_on:
      - db
      - rabbitmq-server
    networks:
      - agenda-network

networks:
  agenda-network:
    driver: bridge